### ISSUE TITLE
Autogrow4 for peptide design?

### ISSUE THREAD

**Issue by TommyBiomodellingAU** [durrantlab/autogrow4#1]
Is it possible to use or modify Autogrow4 to work for _de novo_ peptide design?

**Comment by jacobdurrant** [comment]
Hi Tommy,

Thanks for reaching out! Modifying AutoGrow4 to work for de novo peptide design should be possible. One approach would be to modify the reaction library so it only performs peptide linkages. You could then use single amino acids or small peptides as starting structures, and a library of amino acids (natural or unnatural) for additions. It would likely require some modification to the code, but it should be doable.

Hope this helps,
Jacob
